//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SauceLabsAutomation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VM")]
        public string SauceConnectCmdRelayType {
            get {
                return ((string)(this["SauceConnectCmdRelayType"]));
            }
            set {
                this["SauceConnectCmdRelayType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@ondemand.saucelabs.com:80")]
        public string seleniumURI {
            get {
                return ((string)(this["seleniumURI"]));
            }
            set {
                this["seleniumURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@192.168.200.70:4445")]
        public string vmSeleniumURI {
            get {
                return ((string)(this["vmSeleniumURI"]));
            }
            set {
                this["vmSeleniumURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@localhost:4445")]
        public string localSeleniumURI {
            get {
                return ((string)(this["localSeleniumURI"]));
            }
            set {
                this["localSeleniumURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lottotestnz")]
        public string sauceUname {
            get {
                return ((string)(this["sauceUname"]));
            }
            set {
                this["sauceUname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4441f476-39c5-419f-9b4b-437e8323d461")]
        public string sauceUkay {
            get {
                return ((string)(this["sauceUkay"]));
            }
            set {
                this["sauceUkay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sauce-storage:mylotto-cat1.apk")]
        public string sauce_AndroidAPK_filename {
            get {
                return ((string)(this["sauce_AndroidAPK_filename"]));
            }
            set {
                this["sauce_AndroidAPK_filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("co.nz.mylotto.cat1")]
        public string sauce_AndroidAPK_appPackage {
            get {
                return ((string)(this["sauce_AndroidAPK_appPackage"]));
            }
            set {
                this["sauce_AndroidAPK_appPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("co.nz.mylotto.MainActivity")]
        public string sauce_AndroidAPK_appActivity {
            get {
                return ((string)(this["sauce_AndroidAPK_appActivity"]));
            }
            set {
                this["sauce_AndroidAPK_appActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sauce-storage:LottoNZ.zip")]
        public string sauce_IOSIPA_filename {
            get {
                return ((string)(this["sauce_IOSIPA_filename"]));
            }
            set {
                this["sauce_IOSIPA_filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WEB_Browser {
            get {
                return ((string)(this["WEB_Browser"]));
            }
            set {
                this["WEB_Browser"] = value;
            }
        }
    }
}
